version: "3.9"

networks:
  arbre32-net:

volumes:
  db_data:
  grafana_data:

services:

  database:
    image: postgres:15
    container_name: arbre32-db
    restart: always
    environment:
      POSTGRES_DB: arbre32
      POSTGRES_USER: arbre_user
      POSTGRES_PASSWORD: arbre_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - arbre32-net

  backend:
    image: tchenn/arbre32-backend
    container_name: arbre32-backend
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/arbre32
      SPRING_DATASOURCE_USERNAME: arbre_user
      SPRING_DATASOURCE_PASSWORD: arbre_pass
    expose:
      - "8080"
    networks:
      - arbre32-net

  prometheus:
    image: prom/prometheus
    container_name: arbre32-prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - arbre32-net

  grafana:
    image: grafana/grafana
    container_name: arbre32-grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    networks:
      - arbre32-net

  nginx:
    image: nginx:alpine
    container_name: arbre32-nginx
    restart: always
    depends_on:
      - backend
      - grafana
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - arbre32-net
