
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arbre32
    username: postgres
    password: 1221Studi@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: "THIS_IS_A_DEV_SECRET_CHANGE_IT_IN_PRODUCTION_1234567890"
    expMinutes: 120
