
name: CI/CD Arbre32

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build backend
    - name: Build backend
      run: |
        cd api
        mvn -B -DskipTests clean package

    # Build frontend
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Build Docker images
    - name: Build Docker images
      run: docker-compose build

  push-to-registry:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets_DOCKERHUB_USER }}
        password: ${{ secrets_DOCKERHUB_TOKEN }}

    - name: Build & Push backend
      run: |
        docker build -t ${{ secrets_DOCKERHUB_USER }}/arbre32-backend:latest ./api
        docker push ${{ secrets_DOCKERHUB_USER }}/arbre32-backend:latest

    - name: Build & Push frontend
      run: |
        docker build -t ${{ secrets_DOCKERHUB_USER }}/arbre32-frontend:latest ./frontend
        docker push ${{ secrets_DOCKERHUB_USER }}/arbre32-frontend:latest
