name: CI/CD Arbre32

on:
  push:
    branches: [ "master" ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:

    # Checkout du repo
    - uses: actions/checkout@v3

    # Installe Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # -------------------------------
    # BUILD MODULE CORE
    # -------------------------------
    - name: Build core module
      run: |
        cd core
        mvn -B -DskipTests clean install

    # -------------------------------
    # BUILD BACKEND (API)
    # -------------------------------
    - name: Build backend module (API)
      run: |
        cd api
        mvn -B -DskipTests clean package

    # -------------------------------
    # BUILD FRONTEND (REACT)
    # -------------------------------
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # -------------------------------
    # DOCKER COMPOSE BUILD
    # -------------------------------
    - name: Build Docker images
      run: docker-compose build


  push-to-registry:
    needs: build-test
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    # Login DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # PUSH BACKEND IMAGE
    - name: Build & Push backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/arbre32-backend:latest ./api
        docker push ${{ secrets.DOCKERHUB_USER }}/arbre32-backend:latest

    # PUSH FRONTEND IMAGE
    - name: Build & Push frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/arbre32-frontend:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USER }}/arbre32-frontend:latest
